version: '3'

services:

    backup:
      image: samejack/backup:latest
      restart: always
      build:
        context: ./
      environment:
        - TZ=Asia/Taipei
        - JOB_SCHEDULE=27 4 * * *
        - BACKUP_PATH=/mnt/backup
        - PROJECT_NAME=production

        - FILE_BACKUP_ENABLED=yes
        - FILE_BACKUP_ROLL_DAY=14
        - FILE_PATH=/backup-files

        - MYSQL_BACKUP_ENABLED=yes
        - MYSQL_BACKUP_ROLL_DAY=14
        - MYSQL_USER=default
        - MYSQL_PASSWORD=default_secure
        - MYSQL_DATABASE=default
        - MYSQL_HOST=mysql
        - MYSQL_PORT=3306

        - AWS_ACCESS_KEY_ID=aws-key-id
        - AWS_SECRET_ACCESS_KEY=aws-secret-key
        - AWS_S3_UPLOAD_ENABLED=no
        - AWS_S3_BUCKET=your-backet-name
        - AWS_S3_OBJECT_PREFIX=/backup

      volumes:
        - ./storage/backup:/mnt/backup
        - /home:/backup-files:ro
